### ISSUE TITLE
Vimeo V3 API & Better Thumbnails

### ISSUE THREAD

**Issue by jcohlmeyer** [jrc9designstudio/statamic-video-embed#10]
Use the V3 API to get more of the available thumbnails from Vimeo and deduce the larger thumbnail sizes from YouTube based on their url pattern and store them in an array.

Work started here: https://github.com/jrc9designstudio/statamic-video-embed/pull/9

```
thumbnails:
  -
    url: https://vimeo.com/thumbnail
    width: 1200
    height: 640
  -
    url: https://vimeo.com/other_thumbnail
    width: 640
    height: 480
```
